# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfiles', '0002_auto_20160722_0025'),
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libro_libreria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.LibroLibreria')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=50)),
                ('leida', models.BooleanField(default=False)),
                ('librolibreria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primer_libro', to='libros.LibroLibreria')),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to='perfiles.Perfil')),
                ('segundo_librolibreria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segundo_libro', to='libros.LibroLibreria')),
                ('segundo_perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segundo_perfil', to='perfiles.Perfil')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
