# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='activa',
            field=models.BooleanField(default=False),
        ),
    ]
